#!/usr/bin/env bash
set -Eeuo pipefail
source "$(dirname "${0}")/globals"

! check_command guestfish git && exit

#
# Globals
#

# export LIBGUESTFS_DEBUG=1
# export LIBGUESTFS_TRACE=1


#
# Define helper functions
#

function do_cleanup {
  show_info "Cleaning up..." >&2
  if test "${GUESTFISH_PID}" != ""; then
    guestfish --remote -- exit >/dev/null 2>&1 || true
  fi
  rm -rf "${WORK}"
}


#
# guestfish script helpers
#

function fish {
  show_info "# $*" >&2
  guestfish --remote -- "$@"    || exit 3
}

function fish_init {
  local format

  case "${OPENCORE_QCOW2}" in
    *.raw)
      format="raw"
      ;;
    *)
      format="qcow2"
      ;;
  esac

  show_info "Creating and adding disk image." >&2
  fish disk-create "${BUILD_DIR}/${OPENCORE_QCOW2}" "${format}" 384M
  fish add "${BUILD_DIR}/${OPENCORE_QCOW2}"
  fish run
}

function fish_finish {
  fish umount-all
}


#
# Run sanity checks
#

if test ! -f "${OPENCORE_DIR}/${CONFIG_LIST}.in"; then
  show_error "ERROR: ${CONFIG_LIST@Q} not found. Exiting." >&2
  exit 3
fi

if test -f "${OPENCORE_QCOW2}"; then
  show_error "ERROR: ${OPENCORE_QCOW2@Q} exists. Exiting." >&2
  exit 3
fi


#
# Main
#

pushd "${OPENCORE_DIR}" >/dev/null

# create work dir
WORK="$(mktemp -d)"
trap 'do_cleanup' EXIT INT TERM ERR

# generate plist config
sed -e \
  "s|##RESOLUTION##|${RESOLUTION}|g" \
  "${OPENCORE_DIR}/${CONFIG_LIST}.in" > "${BUILD_DIR}/${CONFIG_LIST}"

show_info "Copying files from local folder to image." >&2
cp -a "${OPENCORE_DIR}/EFI" "${WORK}"

export LIBGUESTFS_BACKEND=direct
eval "$(guestfish --listen)"
if test "${GUESTFISH_PID}" = ""; then
  show_error "ERROR: Starting guestfish failed. Exiting." >&2
  exit 3
fi

show_info "Downloading OcBinaryData..." >&2
git submodule update --init

fish_init

show_info "partitioning disk image" >&2
fish part-init /dev/sda gpt
fish part-add /dev/sda p 2048 300000
fish part-add /dev/sda p 302048 -2048
fish part-set-gpt-type /dev/sda 1 C12A7328-F81F-11D2-BA4B-00A0C93EC93B
fish part-set-bootable /dev/sda 1 true
fish mkfs vfat /dev/sda1 label:EFI
fish mkfs vfat /dev/sda2 label:OpenCore
fish mount /dev/sda2 /
fish mkdir /ESP
fish mount /dev/sda1 /ESP

show_info "copy files to disk image" >&2
cp -v "${BUILD_DIR}/${CONFIG_LIST}" "${WORK}/config.plist"
fish mkdir /ESP/EFI
fish mkdir /ESP/EFI/OC
fish mkdir /ESP/EFI/OC/Kexts
fish mkdir /ESP/EFI/OC/ACPI
fish mkdir /ESP/EFI/OC/Resources
fish mkdir /ESP/EFI/OC/Tools
fish copy-in "${WORK}/EFI/BOOT" /ESP/EFI
fish copy-in "${WORK}/EFI/OC/OpenCore.efi" /ESP/EFI/OC
fish copy-in "${WORK}/EFI/OC/Drivers" /ESP/EFI/OC/
fish copy-in "${WORK}/EFI/OC/Kexts" /ESP/EFI/OC/
fish copy-in "${WORK}/EFI/OC/ACPI" /ESP/EFI/OC/
fish copy-in "${OPENCORE_DIR}/OcBinaryData/Resources" /ESP/EFI/OC/
fish copy-in "${WORK}/EFI/OC/Tools" /ESP/EFI/OC/
fish copy-in "${WORK}/config.plist" /ESP/EFI/OC/

fish find /ESP/
fish_finish
