#! /bin/bash

ROOT="$(basename "${0}")"
KVM_DIR="${HOME}/.local/libvirt/images"
SIZE=100G
MACOS_QCOW2=macos.qcow2
OVMF_CODE=/usr/share/edk2-ovmf/x64/OVMF_CODE.fd
NVRAM_VARS=/var/lib/libvirt/qemu/nvram/MACOS_VARS.fd
OPENCORE_QCOW2=opencore.qcow2
VIRSH_XML=macOS.xml
CONFIG_LIST=config.plist
RESOLUTION=1920x1080
BUILD_DIR="${ROOT}/_build"
OPENCORE_DIR="${ROOT}/src/OpenCore"
SCRIPT_DIR="${ROOT}/scripts"

export ROOT
export KVM_DIR
export SIZE
export MACOS_QCOW2
export OVMF_CODE
export NVRAM_VARS
export OPENCORE_QCOW2
export VIRSH_XML
export CONFIG_LIST
export RESOLUTION
export BUILD_DIR
export OPENCORE_DIR
export SCRIPT_DIR
