#! /bin/bash
set -eu
source globals

if ! [ -d "${BUILD_DIR}" ]; then
  echo "ERROR: build directory missing. Exiting."
  exit 1
fi

if [ -f BaseSystem.img ] && [ -f "${MACOS_QCOW2}" ] && \
   [ -f "${OPENCORE_QCOW2}" ] && [ -f "${VIRSH_XML}" ] && \
   [ "${KVM_DIR}" ]; then
  pushd "${BUILD_DIR}" >/dev/null
  cp -vf BaseSystem.img "${VIRSH_XML}" "${KVM_DIR}"
  cp -vf --sparse=always "${MACOS_QCOW2}" "${OPENCORE_QCOW2}" "${KVM_DIR}"
  popd >/dev/null

  pushd "${KVM_DIR}" >/dev/null
  virt-xml-validate "${VIRSH_XML}"
  virsh --connect qemu:///system define "${VIRSH_XML}"
  popd >/dev/null
fi

