#! /bin/bash
set -eu
source globals

! check_command virsh virt-xml-validate && exit 3

if ! [ -d "${BUILD_DIR}" ]; then
  show_error "ERROR: build directory ${BUILD_DIR@Q} missing. Exiting." >&2
  exit 1
fi

if [ -f BaseSystem.img ] && [ -f "${MACOS_QCOW2}" ] && \
   [ -f "${OPENCORE_QCOW2}" ] && [ -f "${VIRSH_XML}" ] && \
   [ "${KVM_DIR}" ]; then
  pushd "${BUILD_DIR}" >/dev/null
  cp -vf BaseSystem.img "${KVM_DIR}"
  cp -vf --sparse=always "${MACOS_QCOW2}" "${OPENCORE_QCOW2}" "${KVM_DIR}"
  virt-xml-validate "${VIRSH_XML}"
  virsh --connect qemu:///system define "${VIRSH_XML}"
  popd >/dev/null
fi

